apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: bedrock-prod-data
  namespace: bedrock-prod
  labels:
    k8s-app: bedrock-prod-data
spec:
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 5
    type: RollingUpdate
  selector:
    matchLabels:
      name: bedrock-prod-data
  template:
    metadata:
      labels:
        name: bedrock-prod-data
    spec:
      imagePullSecrets:
        - name: dockerhub-registry
      containers:
      - name: bedrock-prod-data
        image: mozmeao/bedrock:a4f76e6a2608b9cda05bd9f08ba3477d64a10c4c
        imagePullPolicy: IfNotPresent
        args:
          - ./bin/run-file-clock.sh
        command:
          - /bin/bash
          - -c
        env:
          - name: AWS_DB_S3_BUCKET
            value: bedrock-db-prod
          - name: CLUSTER_NAME
            valueFrom:
              configMapKeyRef:
                name: bedrock-prod-configmap
                key: CLUSTER_NAME
          - name: DB_DOWNLOAD_IGNORE_GIT
            value: "False"
          - name: DEBUG
            value: "False"
          - name: DEV
            value: "False"
          - name: LOGLEVEL
            value: info
          - name: NEW_RELIC_APP_NAME
            valueFrom:
              configMapKeyRef:
                name: bedrock-prod-configmap
                key: NEW_RELIC_APP_NAME
          - name: NEW_RELIC_LICENSE_KEY
            valueFrom:
              secretKeyRef:
                key: new-relic-license-key
                name: bedrock-prod-secrets
          - name: PROD
            value: "True"
          - name: SECRET_KEY
            valueFrom:
              secretKeyRef:
                key: secret-key
                name: bedrock-prod-secrets
          - name: SENTRY_DSN
            value: "https://45ad5d426da7480081831c053ca02cac@o1069899.ingest.sentry.io/6249535"
          - name: SENTRY_FRONTEND_DSN
            value: "https://c3ab8514873549d5b3785ebc7fb83c80@o1069899.ingest.sentry.io/6260331"
          - name: STATSD_CLIENT
            value: django_statsd.clients.normal
        resources:
          limits:
            cpu: 350m
            memory: 250Mi
          requests:
            cpu: 200m
            memory: 150Mi
        volumeMounts:
        - name: data
          mountPath: /app/data
      priorityClassName: high-priority-preempting
      terminationGracePeriodSeconds: 30
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 0
      volumes:
      - name: data
        hostPath:
          path: /var/lib/bedrock-prod/data
