apiVersion: v1
kind: Service
metadata:
  labels:
    app: bedrock-prod
  name: bedrock-prod-nodeport
  namespace: bedrock-prod
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8000
    nodePort: 32249
  selector:
    app: bedrock-prod
    type: web
  sessionAffinity: None
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: bedrock-pocket-prod
  name: bedrock-pocket-prod-nodeport
  namespace: bedrock-prod
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8000
    nodePort: 32250
  selector:
    app: bedrock-pocket-prod
    type: web
  sessionAffinity: None
  type: NodePort
