apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt
  namespace: bedrock-prod
spec:
  acme:
    # You must replace this email address with your own.
    # Let's Encrypt will use this to contact you about expiring
    # certificates, and issues related to your account.
    email: it-se@mozilla.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      # Secret resource used to store the account's private key.
      name: letsencrypt
    solvers:
      - dns01:
          cnameStrategy: Follow
          route53:
            region: us-west-2
---
apiVersion: v1
kind: Service
metadata:
  name: bedrock-prod-ingress
  namespace: bedrock-prod
spec:
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    app: bedrock-prod
    type: web
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/issuer: letsencrypt
  name: bedrock-prod
  namespace: bedrock-prod
spec:
  rules:
    - host: "bedrock.prod.fr.moz.works"
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: bedrock-prod-ingress
                port:
                  number: 8000
    - host: "bedrock-prod.moz.works"
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: bedrock-prod-ingress
                port:
                  number: 8000
    - host: "www.mozilla.org"
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: bedrock-prod-ingress
                port:
                  number: 8000
    - host: "www.mozorg.moz.works"
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: bedrock-prod-ingress
                port:
                  number: 8000
  # This section is only required if TLS is to be enabled for the Ingress
  tls:
      - hosts:
          - "bedrock.prod.fr.moz.works"
          - "bedrock-prod.moz.works"
          - "www.mozorg.moz.works"
          - "www.mozilla.org"
        secretName: bedrock-tls
