include:
  - .gitlab/gitlab_jobs.yml

.environment_override:
  before_script:
    - export BASE_URL=$ENVIRONMENT_URL

test-cdn:
  # to run only one cdn test at a time
  resource_group: cdn-tests
  variables:
    MARK_EXPRESSION: "cdn and not cdnprod"
  extends:
    - .test
    - .environment_override
    - .headless
