apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: bedrock-dev
    type: clock
  name: bedrock-dev-clock
  namespace: bedrock-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bedrock-dev
      type: clock
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: bedrock-dev
        type: clock
      name: bedrock-dev-clock
      namespace: bedrock-dev
    spec:
      imagePullSecrets:
        - name: dockerhub-registry
      containers:
        - args:
            - ./bin/run-db-clock.sh
          command:
            - /bin/bash
            - -c
          env:
            - name: ALLOWED_HOSTS
              value: "*"
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  key: aws-access-key-id
                  name: bedrock-dev-secrets
            - name: AWS_DB_S3_BUCKET
              value: bedrock-db-dev
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  key: aws-secret-access-key
                  name: bedrock-dev-secrets
            - name: BASKET_API_KEY
              valueFrom:
                secretKeyRef:
                  key: basket-api-key
                  name: bedrock-dev-secrets
            - name: BASKET_URL
              value: https://basket-dev.allizom.org
            - name: CONTENTFUL_NOTIFICATION_QUEUE_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  key: contentful-notification-access-key-id
                  name: bedrock-dev-secrets
            - name: CONTENTFUL_NOTIFICATION_QUEUE_REGION
              value: us-west-2
            - name: CONTENTFUL_NOTIFICATION_QUEUE_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  key: contentful-notification-secret-access-key
                  name: bedrock-dev-secrets
            - name: CONTENTFUL_NOTIFICATION_QUEUE_URL
              valueFrom:
                secretKeyRef:
                  key: contentful-notification-queue-url
                  name: bedrock-dev-secrets
            - name: CONTENTFUL_SPACE_ID
              valueFrom:
                secretKeyRef:
                  key: contentful-space-id
                  name: bedrock-dev-secrets
            - name: CONTENTFUL_SPACE_KEY
              valueFrom:
                secretKeyRef:
                  key: contentful-space-key
                  name: bedrock-dev-secrets
            - name: CONTENTFUL_ENVIRONMENT
              value: "pre-production"
            - name: CLUSTER_NAME
              valueFrom:
                configMapKeyRef:
                  name: bedrock-dev-configmap
                  key: CLUSTER_NAME
            - name: CSP_REPORT_ENABLE
              value: "True"
            - name: DB_UPDATE_SCRIPT_DMS_URL
              valueFrom:
                secretKeyRef:
                  key: dead-mans-snitch-db-updates-url
                  name: bedrock-dev-secrets
            - name: DEBUG
              value: "False"
            - name: DEIS_DOMAIN
              valueFrom:
                configMapKeyRef:
                  name: bedrock-dev-configmap
                  key: DEIS_DOMAIN
            - name: DEV
              value: "True"
            - name: DISABLE_SSL
              value: "False"
            - name: EMAIL_HOST
              valueFrom:
                secretKeyRef:
                  key: email-host
                  name: bedrock-dev-secrets
            - name: EMAIL_HOST_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: email-host-password
                  name: bedrock-dev-secrets
            - name: EMAIL_HOST_USER
              valueFrom:
                secretKeyRef:
                  key: email-host-user
                  name: bedrock-dev-secrets
            - name: EMAIL_PORT
              valueFrom:
                secretKeyRef:
                  key: email-port
                  name: bedrock-dev-secrets
            - name: EMAIL_USE_TLS
              valueFrom:
                secretKeyRef:
                  key: email-use-tls
                  name: bedrock-dev-secrets
            - name: ENABLE_CSP_MIDDLEWARE
              value: "True"
            - name: ENABLE_HOSTNAME_MIDDLEWARE
              value: "True"
            - name: GTM_CONTAINER_ID
              value: GTM-MW3R8V
            - name: HTTPS
              value: "on"
            - name: L10N_CRON
              value: "True"
            - name: LEGAL_DOCS_BRANCH
              value: "main"
            - name: LEGAL_DOCS_DMS_URL
              valueFrom:
                secretKeyRef:
                  key: legal-docs-dms-url
                  name: bedrock-dev-secrets
            - name: LOGLEVEL
              value: info
            - name: MOFO_SECURITY_ADVISORIES_BRANCH
              value: master
            - name: MOFO_SECURITY_ADVISORIES_PATH
              value: /tmp/mofo_security_advisories
            - name: NEWRELIC_PYTHON_INI_FILE
              value: newrelic.ini
            - name: NEW_RELIC_APP_NAME
              valueFrom:
                configMapKeyRef:
                  name: bedrock-dev-configmap
                  key: NEW_RELIC_APP_NAME
            - name: NEW_RELIC_LICENSE_KEY
              valueFrom:
                secretKeyRef:
                  key: new-relic-license-key
                  name: bedrock-dev-secrets
            - name: POCKET_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  key: pocket-access-token
                  name: bedrock-dev-secrets
            - name: POCKET_CONSUMER_KEY
              valueFrom:
                secretKeyRef:
                  key: pocket-consumer-key
                  name: bedrock-dev-secrets
            - name: PROD
              value: "True"
            - name: RUN_SUPERVISOR
              value: "True"
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  key: secret-key
                  name: bedrock-dev-secrets
            - name: SECURE_BROWSER_XSS_FILTER
              value: "True"
            - name: SECURE_HSTS_SECONDS
              value: "31536000"
            - name: SECURE_SSL_REDIRECT
              value: "True"
            - name: SENTRY_DSN
              value: "https://c1f94ae1b8c54ed0adcf223328157caf@o1069899.ingest.sentry.io/6260211"
            - name: STATSD_CLIENT
              value: django_statsd.clients.normal
            - name: SWITCH_NEWSLETTER_MAINTENANCE_MODE
              value: "False"
            - name: TWITTER_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  key: twitter-access-token
                  name: bedrock-dev-secrets
            - name: TWITTER_ACCESS_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  key: twitter-access-token-secret
                  name: bedrock-dev-secrets
            - name: TWITTER_CONSUMER_KEY
              valueFrom:
                secretKeyRef:
                  key: twitter-consumer-key
                  name: bedrock-dev-secrets
            - name: TWITTER_CONSUMER_SECRET
              valueFrom:
                secretKeyRef:
                  key: twitter-consumer-secret
                  name: bedrock-dev-secrets
            - name: WWW_CONFIG_BRANCH
              value: "main"
          image: mozmeao/bedrock:ba15cb0bfede361ae7597cfd2d3bac8fc0262e3b
          imagePullPolicy: IfNotPresent
          name: bedrock-dev-clock
          resources:
            limits:
              cpu: 500m
              memory: 300Mi
            requests:
              cpu: 250m
              memory: 120Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
