apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: bedrock-dev
    type: web
  name: bedrock-dev-web
  namespace: bedrock-dev
spec:
  replicas: 5
  selector:
    matchLabels:
      app: bedrock-dev
      type: web
  strategy:
    rollingUpdate:
      maxSurge: 5
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: bedrock-dev
        type: web
      name: bedrock-dev-web
      namespace: bedrock-dev
    spec:
      imagePullSecrets:
        - name: dockerhub-registry
      containers:
      - args:
        - ./bin/run-prod.sh
        command:
        - /bin/bash
        - -c
        env:
        - name: ALLOWED_HOSTS
          value: "*"
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              key: aws-access-key-id
              name: bedrock-dev-secrets
        - name: AWS_DB_S3_BUCKET
          value: bedrock-db-dev
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key: aws-secret-access-key
              name: bedrock-dev-secrets
        - name: BASKET_API_KEY
          valueFrom:
            secretKeyRef:
              key: basket-api-key
              name: bedrock-dev-secrets
        - name: BASKET_URL
          value: https://basket-dev.allizom.org
        - name: CLUSTER_NAME
          valueFrom:
            configMapKeyRef:
              name: bedrock-dev-configmap
              key: CLUSTER_NAME
        - name: CONTENTFUL_SPACE_ID
          valueFrom:
            secretKeyRef:
              key: contentful-space-id
              name: bedrock-dev-secrets
        - name: CONTENTFUL_SPACE_KEY
          valueFrom:
            secretKeyRef:
              key: contentful-space-key
              name: bedrock-dev-secrets
        - name: CSP_DEFAULT_SRC
          value: "*.allizom.org"
        - name: CSP_REPORT_ENABLE
          value: "True"
        - name: DEBUG
          value: "False"
        - name: DEIS_DOMAIN
          valueFrom:
            configMapKeyRef:
              name: bedrock-dev-configmap
              key: DEIS_DOMAIN
        - name: DEV
          value: "True"
        - name: DISABLE_SSL
          value: "False"
        - name: EMAIL_HOST
          valueFrom:
            secretKeyRef:
              key: email-host
              name: bedrock-dev-secrets
        - name: EMAIL_HOST_PASSWORD
          valueFrom:
            secretKeyRef:
              key: email-host-password
              name: bedrock-dev-secrets
        - name: EMAIL_HOST_USER
          valueFrom:
            secretKeyRef:
              key: email-host-user
              name: bedrock-dev-secrets
        - name: EMAIL_PORT
          valueFrom:
            secretKeyRef:
              key: email-port
              name: bedrock-dev-secrets
        - name: EMAIL_USE_TLS
          valueFrom:
            secretKeyRef:
              key: email-use-tls
              name: bedrock-dev-secrets
        - name: ENABLE_CSP_MIDDLEWARE
          value: "True"
        - name: ENABLE_HOSTNAME_MIDDLEWARE
          value: "True"
        - name: GTM_CONTAINER_ID
          value: GTM-MW3R8V
        - name: HTTPS
          value: "on"
        - name: L10N_CRON
          value: "True"
        - name: LOGLEVEL
          value: info
        - name: MOFO_SECURITY_ADVISORIES_BRANCH
          value: testing
        - name: MOFO_SECURITY_ADVISORIES_PATH
          value: /tmp/mofo_security_advisories
        - name: NEW_RELIC_APP_NAME
          valueFrom:
            configMapKeyRef:
              name: bedrock-dev-configmap
              key: NEW_RELIC_APP_NAME
        - name: NEW_RELIC_LICENSE_KEY
          valueFrom:
            secretKeyRef:
              key: new-relic-license-key
              name: bedrock-dev-secrets
        - name: PROD
          value: "True"
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              key: secret-key
              name: bedrock-dev-secrets
        - name: SECURE_BROWSER_XSS_FILTER
          value: "True"
        - name: SECURE_HSTS_SECONDS
          value: "31536000"
        - name: SECURE_SSL_REDIRECT
          value: "True"
        - name: SENTRY_DSN
          value: "https://c7764face5354517befaee2e56b63cfb@sentry.prod.mozaws.net/122"
        - name: STATIC_URL
          value: "https://www-dev.allizom.org/media/"
        - name: STATSD_CLIENT
          value: django_statsd.clients.normal
        - name: SWITCH_NEWSLETTER_MAINTENANCE_MODE
          value: "False"
        - name: FXA_ENDPOINT
          value: "https://accounts.stage.mozaws.net/"
        - name: VPN_ENDPOINT
          value: "https://stage-vpn.guardian.nonprod.cloudops.mozgcp.net/"
        - name: TWITTER_ACCESS_TOKEN
          valueFrom:
            secretKeyRef:
              key: twitter-access-token
              name: bedrock-dev-secrets
        - name: TWITTER_ACCESS_TOKEN_SECRET
          valueFrom:
            secretKeyRef:
              key: twitter-access-token-secret
              name: bedrock-dev-secrets
        - name: TWITTER_CONSUMER_KEY
          valueFrom:
            secretKeyRef:
              key: twitter-consumer-key
              name: bedrock-dev-secrets
        - name: TWITTER_CONSUMER_SECRET
          valueFrom:
            secretKeyRef:
              key: twitter-consumer-secret
              name: bedrock-dev-secrets
        image: mozmeao/bedrock:332fd911d0dac7d2574dc6f6e996c0d57cb2fd5e
        imagePullPolicy: IfNotPresent
        name: bedrock-dev-web
        ports:
          - containerPort: 8000
        livenessProbe:
          failureThreshold: 4
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 5
          httpGet:
            path: /healthz/
            scheme: HTTP
            port: 8000
        readinessProbe:
          failureThreshold: 1
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 5
          httpGet:
            path: /readiness/
            scheme: HTTP
            port: 8000
        resources:
          limits:
            cpu: 1250m
            memory: 800Mi
          requests:
            cpu: 1000m
            memory: 600Mi
        volumeMounts:
          - name: data
            mountPath: /app/data
            readOnly: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: data
          hostPath:
            type: Directory
            path: /var/lib/bedrock-dev/data
