name: Mirror repo
on: [push]

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
       - name: mirror in gitlab
         uses: actions/checkout@v3
         with:
          fetch-depth: 0
       - uses: yesolutions/mirror-action@v0.6.0
         with:
            REMOTE: 'https://gitlab.com/mozmeao/www-config.git'
            GIT_USERNAME: ${{ secrets.GITLAB_USERNAME }}
            GIT_PASSWORD: ${{ secrets.GITLAB_PASSWORD }}
